# Generated by Django 4.2.2 on 2023-06-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t3',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('pay', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't3',
            },
        ),
    ]
