# Generated by Django 4.2.2 on 2023-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cell_barcode', models.CharField(max_length=32)),
                ('cell_type', models.CharField(max_length=20)),
                ('zone', models.IntegerField()),
                ('run_id', models.CharField(max_length=12)),
                ('time_point', models.IntegerField()),
                ('UMAP_X', models.DecimalField(decimal_places=18, max_digits=32)),
                ('UMAP_Y', models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                'db_table': 'tliver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='t1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cell_barcode', models.CharField(max_length=32)),
                ('cell_type', models.CharField(max_length=20)),
                ('zone', models.IntegerField()),
                ('run_id', models.CharField(max_length=12)),
                ('time_point', models.IntegerField()),
                ('UMAP_X', models.FloatField()),
                ('UMAP_Y', models.FloatField()),
            ],
            options={
                'db_table': 'tliverjinlianji',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='t3',
            options={'managed': True},
        ),
    ]
