# Generated by Django 4.2.2 on 2023-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_tliver_t1_alter_t3_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiterData',
            fields=[
                ('Liter_pmid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Liter_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Liter_abstract', models.TextField(blank=True, null=True)),
                ('Liter_publication', models.TextField(blank=True, null=True)),
                ('Liter_content', models.TextField(blank=True, null=True)),
                ('Liter_data', models.TextField(blank=True, null=True)),
                ('Sample_info', models.TextField(blank=True, null=True)),
                ('Species', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tissue', models.CharField(blank=True, max_length=1000, null=True)),
                ('Number_cells', models.CharField(blank=True, max_length=100, null=True)),
                ('Cell_types', models.TextField(blank=True, null=True)),
                ('Method', models.CharField(blank=True, max_length=1000, null=True)),
                ('Markers', models.TextField(blank=True, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celldb_literaturemeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tliver1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cell_barcode', models.CharField(max_length=32)),
                ('cell_type', models.CharField(max_length=20)),
                ('zone', models.IntegerField()),
                ('run_id', models.CharField(max_length=12)),
                ('time_point', models.IntegerField()),
                ('UMAP_X', models.CharField(max_length=32)),
                ('UMAP_Y', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tliver1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'celldb_uploadedfile',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='t1',
        ),
    ]
